### ISSUE TITLE
Not finding `libsndfile` 

### ISSUE THREAD

**Issue by jpenney** [vokimon/python-wavefile#19]
I'm having an issue where no matter what I do it doesn't seem able to find `libsndfile` when using a virtualenv.

I'm on a Mac, so it's possible it's specific to that, but I wonder if `libsndfile.py` could try something simpler as it's first attempt, since this works fine, then if this doesn't work try the platform specific versions you have currently.

```
_lib = ct.CDLL(find_library('libsndfile'))
```

**Comment by vokimon** [comment]
Could you provide some more details. The actual error message, how did you install the C libsndfile library, the environment vars needed in Mac to locate the dylibs... For Mac i just integrated the patch for a contributor. So if you provide an enhancement it will be wellcome because i cannot do the testing.

**Comment by vokimon** [comment]
No feedback in more than a year, so i close the issue. I guess it was a problem on how dylibs are located. But no way to test it myself.
