### ISSUE TITLE
RuntimeError: StopIteration

### ISSUE THREAD

**Issue by dgrigonis** [vokimon/python-wavefile#31]
```
wr = WaveReader(self.path)
for block in wr.read_iter(size=BUFFER_SIZE):
    pass
```
RuntimeError: generator raised StopIteration

This is an unusual Error for generators used in the `for` loop. I looked at the source and the method itself seems fine, so I would guess there is some sort of error catch wrapper around it?

Or is it an expected behavior?
I am running Python 3.11 by the way.

As I use it in a class I did fix it by:
```
def __next__(self):
    try:
        return next(wf.read_iter)
    except RuntimeError:
        raise StopIteraton
```
But it's what it should have done in the first place, isn't it? Not `StopIteration` wrapped in `RuntimeError`

On another note, great library. I did some benchmarking versus `cpython.wave` and `soundfile`:
For PCM, it performs as well as python.wave and twice as fast as `soundfile`. For 32float - same results. This is with 64 sample buffer by the way.
```
# PATH_WAV PCM-16bit
# soundfile, wave, wavefile
# y=[0.29099851 0.13632101 0.12591818]
# n=10, repeat=3
# 
# PATH_WAV32 IEEE 32bit
# soundfile, wavefile
# y=[0.72977822 0.32874212]
# n=100, repeat=3
```

Also, what is a bit unusual is fortran ordering on transposition. It is not pythonic/numpyic and not compliant with libraries such as `sounddevice`. Although Fortran(channels, buffersize).T is exactly the same as Contiguous(buffersize, channels) in all ways, it is still a bit annoying. :)

**Comment by vokimon** [comment]
StopIteration has been deprecated for long time and later Python versions have dropped it. Since most platforms have moved to the later Python versions, this is an urgent bug. I will update the code as soon as possible.

**Comment by vokimon** [comment]
Regarding the comments not related to the bug itself, I thank you for the benchmarks. I am glad to hear that the library still performs well side by others without having optimizing it for a while. In part i guess this is because the lightweight wrapping over  libsndfile and the block by block processing.

I would like to know why you feel that the index ordering is not pythonic. Python and numpy does not know about audio. Indeed if you are block processing you want to split first the channels in order to pass data to, for example an fft. Anyway i am curious but if you want to go deeper, please, i would appreciate that you open a different issue for the topic.

**Comment by vokimon** [comment]
The new release should solve the StopIteration problem. Not using any more Py2 code and now passing tests with python 3.11.
